openapi: 3.0.0
info:
  title: HaitiPay Acceptor API
  description: "# HaitiPay API description\n\n**The HaitiPay platform** is designed to support several types of transactions and payment applications. HaitiPay allows any phone to be used as for electronic transactions, such as bill payment, money transfers to others, point of sale purchases, etc. The HaitiPay platform offers the following features to users:\npurchase goods and services at their favorite local stores. Unbanked merchants will be able to accept payments and formalize their busines[...]"
  contact:
    name: Developer Support
    url: https://wwww.haitipay.com/api.html
    email: devsupport@haitipay.com
  version: '0.1'
servers:
- url: https://sandbox.haitipay.com/api/acceptor/v1
  variables: {}
paths:
  /clients:
    get:
      tags:
      - Clients
      summary: SearchClients
      description: Search for a client
      operationId: SearchClients
      deprecated: false
      security:
      - oauth2:
        - clients_view
  /clients/{clientId}/accounts:
    get:
      tags:
      - Accounts
      summary: SearchClientAccounts
      description: Search client accounts
      operationId: SearchClientAccounts
      deprecated: false
      security:
      - oauth2:
        - client_accounts_view
  /accounts:
    get:
      tags:
      - Accounts
      summary: SearchAccounts
      description: Search accounts
      operationId: SearchAccounts
      deprecated: false
      security:
      - oauth2:
        - accounts_view
  /transactions/cashin/{transactionToken}:
    post:
      tags:
      - Cashin
      summary: CashinMake
      description: Making a Cashin transaction for a Client. ( Client recharges his/her wallet account by first  giving cash to Agent then Agent recharges Client Account with e-money from his Agent Account. E-money is debited from Agent Account and then credited to Client  wallet Account)
      operationId: CashinMake
      deprecated: false
      security:
      - oauth2:
        - cashin
  /transactions/cashin:
    post:
      tags:
      - Cashin
      summary: CashinPreauth
      description: Cashin pre-authorization. Acceptor (Agent or Merchant) needs to do a Preauthorization before making a confirmed Cash-in Transaction. Once Acceptor get pre-authorization token, the pre-authorized transaction needs to be validated by at least 2 Authentification methods using token.
      operationId: CashinPreauth
      deprecated: false
      security:
      - oauth2:
        - cashin
  /transactions/cashout/{transactionToken}:
    post:
      tags:
      - Cashout
      summary: CashoutMake
      description: Cashout transaction
      operationId: CashoutMake
      deprecated: false
      security:
      - oauth2:
        - cashout
  /transactions/cashout:
    post:
      tags:
      - Cashout
      summary: CashoutPreauth
      description: Cashout pre-authorization
      operationId: CashoutPreauth
      deprecated: false
      security:
      - oauth2:
        - cashout
  /transactions/payment/{transactionToken}:
    post:
      tags:
      - Payment
      summary: PaymentMake
      description: Payment transaction
      operationId: PaymentMake
      deprecated: false
      security:
      - oauth2:
        - payment
  /transactions/payment:
    post:
      tags:
      - Payment
      summary: PaymentPreauth
      description: Payment pre-authorization
      operationId: PaymentPreauth
      deprecated: false
      security:
      - oauth2:
        - payment
  /billers:
    get:
      tags:
      - Bill payment
      summary: LoadBillerTree
      description: Bill issuers list
      operationId: LoadBillerTree
      deprecated: false
      security:
      - oauth2:
        - bill_payment
  /transactions/paybill:
    post:
      tags:
      - Bill payment
      summary: InitPaybill
      description: "\n<details>\n  <summary>An example of paybill call flow (click to expand)</summary>\n  \n  ```js\n  function paybill(apiClient, billIssuerId, clientIdentifier) {\n      // initiate paybill transaction\n      let response = apiClient.post(\"/transactions/paybill\", {billIssuerId: billIssuerId, clientIdentifier: clientIdentifier});\n      let transactionToken = response.body.transactionToken;\n      let userSubmittedValues = null;\n  \n      // making multiple preauth\n      wh[...]"
      operationId: InitPaybill
      deprecated: false
      security:
      - oauth2:
        - bill_payment
  /transactions/paybill/{transactionToken}:
    patch:
      tags:
      - Bill payment
      summary: SubmitPaybillInfo
      description: Paybill pre-authorization
      operationId: SubmitPaybillInfo
      deprecated: false
      security:
      - oauth2:
        - bill_payment
    post:
      tags:
      - Bill payment
      summary: Paybill
      description: Paybill transaction
      operationId: Paybill
      deprecated: false
      security:
      - oauth2:
        - bill_payment
  /transactions/reversal:
    post:
      tags:
      - Reversal
      summary: ReversalPreauth
      description: Reversal pre-authorization
      operationId: ReversalPreauth
      deprecated: false
      security:
      - oauth2:
        - reversal
  /transactions/reversal/{transactionToken}:
    post:
      tags:
      - Reversal
      summary: ReversalMake
      description: Reversal transaction
      operationId: ReversalMake
      deprecated: false
      security:
      - oauth2:
        - reversal
  /authentications/{transactionToken}/pincode-acceptor/verify:
    patch:
      tags:
      - Authentication
      summary: VerifyAcceptorPincode
      description: Should be called when requested authentication mode is `PINCODE_ACCEPTOR`
      operationId: VerifyAcceptorPincode
      deprecated: false
      security:
      - oauth2:
        - authentication_pincode_acceptor
  /authentications/{transactionToken}/qr-code/verify:
    patch:
      tags:
      - Authentication
      summary: VerifyQrCode
      description: >
        Should be called when requested authentication mode is `QR_CODE_CLIENT`.


        This endpoint uses [Server Sent Events](#section/Server-Sent-Events)
      operationId: VerifyQrCode
      deprecated: false
      security:
      - oauth2:
        - authentication_qr_code
  /authentications/{transactionToken}:
    delete:
      tags:
      - Authentication
      summary: CancelTransaction
      description: Can cancel an ongoing transaction
      operationId: CancelTransaction
      deprecated: false
      security:
      - oauth2:
        - authentication_cancel
  /authentications/{transactionToken}/otp-client/send:
    patch:
      tags:
      - Authentication
      summary: SendClientOTP
      description: Should be called when requested authentication mode is `OTP_CLIENT`
      operationId: SendClientOTP
      deprecated: false
      security:
      - oauth2:
        - authentication_otp_client
  /authentications/{transactionToken}/pincode-client/verify:
    patch:
      tags:
      - Authentication
      summary: VerifyClientPincode
      description: Should be called when requested authentication mode is `PINCODE_CLIENT`
      operationId: VerifyClientPincode
      deprecated: false
      security:
      - oauth2:
        - authentication_pincode_client
  /authentications/{transactionToken}/otp-client/verify:
    patch:
      tags:
      - Authentication
      summary: VerifyClientOTP
      description: Should be called when requested authentication mode is `OTP_CLIENT`, after that OTP was sent
      operationId: VerifyClientOTP
      deprecated: false
      security:
      - oauth2:
        - authentication_otp_client
  /authentications/{transactionToken}/pincode-client-ivr/verify:
    patch:
      tags:
      - Authentication
      summary: VerifyPincodeClientIVR
      description: >
        Should be called when requested authentication mode is `PINCODE_CLIENT_IVR`.


        This endpoint uses [Server Sent Events](#section/Server-Sent-Events)
      operationId: VerifyPincodeClientIVR
      deprecated: false
      security:
      - oauth2:
        - authentication_pincode_client_ivr
  /authentications/{transactionToken}/nsdt/verify:
    patch:
      tags:
      - Authentication
      summary: VerifyNSDT
      description: >
        Should be called when requested authentication mode is `NSDT_CLIENT`.


        This endpoint uses [Server Sent Events](#section/Server-Sent-Events)


        When event call status is `CONNECTED`, the API Client should start playing NSDT token.


        When event call status is in `SUCCESS`, `HANG_UP`, `TIMEOUT`, the API Client should stop playing NSDT token.
      operationId: VerifyNSDT
      deprecated: false
      security:
      - oauth2:
        - authentication_nsdt
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://sandbox.haitipay.com/api/acceptor/v1/oauth2/token
          scopes:
            clients_view: View clients information
            accounts_view: View acceptor accounts information
            client_accounts_view: View client accounts information
            cashin: Make cashin transaction
            cashout: Make cashout transaction
            bill_payment: Make bill payment transaction
            payment: Make payment transaction
            reversal: Make reversal transaction
            authentication_pincode_acceptor: Authenticate acceptor with it's pincode
            authentication_pincode_client: Authenticate client with it's pincode
            authentication_pincode_client_ivr: Authenticate client with it's pincode through IVR
            authentication_otp_client: Authenticate client with a one time password
            authentication_nsdt: Authenticate client with NSDT
            authentication_qr_code: Authenticate client with QR Code
            authentication_cancel: Cancel an ongoing transaction
            authentication_transaction_code: Generate a transaction code
security:
- oauth2: []
tags:
- name: Clients
  description: ''
- name: Accounts
  description: ''
- name: Cashin
  description: ''
- name: Cashout
  description: ''
- name: Payment
  description: ''
- name: Bill payment
  description: ''
- name: Reversal
  description: ''
- name: Authentication
  description: ''
